<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718160502 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Migration generates user profile';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE profiles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id BIGINT NOT NULL REFERENCES users(id), 
            name VARCHAR(255) NOT NULL,
            surname VARCHAR(255) NOT NULL, 
            status VARCHAR(255) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT now()
        )');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE profiles');
    }
}
