<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718155724 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Migration creates users table and user_role_type ENUM';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TYPE user_role_type AS ENUM (\'user\', \'admin\', \'support\')');
        $this->addSql('CREATE TABLE users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            uuid UUID NOT NULL DEFAULT  uuidv7(), 
            username VARCHAR(255) UNIQUE NOT NULL, 
            email VARCHAR(255) UNIQUE NOT NULL,
            password VARCHAR(255) NOT NULL, 
            role user_role_type NOT NULL DEFAULT \'user\',
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TYPE user_role_type');
    }
}
